apiVersion: v1
kind: Service
metadata:
  name: {{ include "yolosplit-cloud.name" . }}
  labels:
    {{- include "yolosplit-cloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "yolosplit-cloud.selectorLabels" . | nindent 4 }}
  ports:
    - name: wire
      port: {{ .Values.service.port }}
      targetPort: wire
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
