{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "yolosplit-cloud.name" . }}
  labels:
    {{- include "yolosplit-cloud.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "yolosplit-cloud.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
